# Generated by Django 3.2 on 2021-04-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_details_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='complete',
        ),
    ]
