# Generated by Django 3.2 on 2021-04-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_detail_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='isbnNumber',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='detail',
            name='pages',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='detail',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
