# Generated by Django 3.2 on 2021-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210416_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookname',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookname',
            name='isbnNumber',
            field=models.IntegerField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookname',
            name='pages',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookname',
            name='publisher',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookname',
            name='year',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
