# Generated by Django 3.2 on 2021-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accesslevel',
            field=models.TextField(default=1, null=True),
        ),
    ]
