# Generated by Django 3.2 on 2021-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_accesslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accesslevel',
            field=models.CharField(default=1, max_length=2, null=True),
        ),
    ]
