# Generated by Django 3.2 on 2021-04-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
    ]
