# Generated by Django 3.2 on 2021-04-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210422_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookname',
            name='waitlist',
            field=models.IntegerField(null=True),
        ),
    ]
