# Generated by Django 3.2 on 2021-04-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookname',
            name='waitlist',
        ),
        migrations.AddField(
            model_name='bookname',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
